### ISSUE TITLE
verify OTP

### ISSUE THREAD

**Issue by Parables** [variablesign/sms#1]
I sincerely appreciate the work you have done here.

How can OTP messages be verified?

**Comment by variablesign** [comment]
I usually store them along with the phone numbers. Same as the way Laravel
handles password reset (email & token).

And also with time limits so it expires when not used.

**Comment by Parables** [comment]
I see no method in https://github.com/variablesign/sms/blob/master/src/Sms.php to handle that no does the README says anything about that.

OTP messages are sent throught the sms instance, but after receiving the code, the user is to submit it back, where you check whether the code sent back is valid and it hasn't expired and you send a response back to indicte the success or failure of the verification
